---
- name: Playbook control lab
  hosts: webservers
  vars_files: vars.yml
  vars:
    osfamily: RedHat
    memoria: 500    
  tasks:
    - name: gatherin facts
      debug:
        var: ansible_facts

    - name: Fail fast message
      fail:
        msg: Has at least the amount of RAM specified by the {{ min_ram_mb }} 
 
      when:   (osfamily  == "RedHat") and (memoria <= min_ram_mb)
     
    - name: present "{{ item }}" packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"


    - name: Install {{ item }}
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"      
    
    - name: enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ services }}"
              
    #Install all packages

    #Enable and start services

    #Block of config tasks

    #Configure the firewall

  #Add handlers
