---
- name: create administrative users
  hosts: web
  tasks:
  - name: create admin user1
    user:
       name: jerry
       uid: 200
       shell: /bin/bash
       groups: root, wheel
       append: yes
